name: CI/CD PIPELINE TO BULD AND DEPLOY TO TOMCAT

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: validate with maven 
        run:  mvn validate
      - name: compile with maven
        run:   mvn compile 
      - name:  test with maven
        run:  mvn test
      - name: package with maven
        run:  mvn package
      - name: verify war file
        run: ls -lh target/ 
      
      # SONARQUBE CODE QUALITY 
      - name: BUILD, TEST and Sonarqube Scan
        run: |
            mvn clean sonar:sonar \
            -Dsonar.projectKey=train-ticket \
            -Dsonar.host.url="${{secrets.SONAR_HOST_URL}}" \
            -Dsonar.login="${{secrets.SONAR_TOKEN}}"
              -
         
      
         
      
      
           
      
  
