name: CI/CD Pipeline with SonarQube

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      # 1. Checkout Source Code
      - name: Checkout Source
        uses: actions/checkout@v4


      # 2. Setup Java 17
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven


      # 3. Validate
      - name: Validate
        run: mvn validate


      # 4. Compile
      - name: Compile
        run: mvn compile


      # 5. Test
      - name: Test
        run: mvn test


      # 6. Package
      - name: Package
        run: mvn package


      # 7. SonarQube Scan
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn clear verify:verify \
            -Dsonar.projectKey=train \
            -Dsonar.projectName=TrainBook \
            -Dsonar.host.url="$SONAR_HOST_URL" \
            -Dsonar.token="$SONAR_TOKEN"

        
        
      
      

          
      
