name: ci pipeline to build maven
on:
  push:
    branches: master
jobs:
  build-deploy:
     runs-on: ubuntu-latest
     steps:
      - name: checkout code 
        uses: actions/checkout@v5
      - name: set-up jdk 
        uses: actions/setup-java@v5
        with:
           distributions: "termuin"
           java-version:  '17'
      - name: validate with maven
        run: mvn validate

      - name: compile with maven
        run: mvn compile

      - name: test with maven
        run: mvn test

      - name: package with maven
        run: mvn package

      - name: verfiy the war file
        run: ls -lh target/
        
        
        
      
      

          
      
