name: ci pipeline to build the scource code with maven 
on: 
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: set-up jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'   # Updated Java versio
      - name: maven validate
        run: mvn test
      - name: maven compile
        run: mvn compile 
      - name: maven test
        run: mvn test
      - name: maven package
        run: mvn package
        # deploye to tomcat
     
       
 
